version: "2"
services:
  db:
      image: mariadb
      environment:
          - MYSQL_ROOT_PASSWORD=abacaba
          - TZ=Europe/Moscow
      volumes:
          - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
          - ./data:/var/lib/mysql
      ports:
          - 4306:3306
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
          - PMA_HOST=db
          - PMA_USER=root
          - PMA_PASSWORD=abacaba
      restart: always
      ports:
          - 88:80
      links:
          - db
